echo "|Servernaam (primaire DNS):|`hostname -f`|"
echo "|Server Type:|`sudo dmidecode | grep -A3 'System Information' | grep "Product Name" | sed "s/Product Name: //g"`|"
echo "|Jaar van aanschaf:|-|"
echo "|Service Tag:|`sudo dmidecode|grep "Serial Number" | sed -e '2,$d' -e 's/Serial Number: //g'`|"
echo "|Servicecontract:|-|"
echo "|Servicecontractnummer:|-|"
echo "|Servicecontract telefoonnummer:|-|"
echo "|Einddatum servicecontract:|-|"
echo "|Laatste service verzoek:|-|"
echo "|Project:|-|"
echo "|Doel:|-|"
echo "|OS:|`lsb_release -d | cut -f2`|"
echo "|Laatste update / upgrade:|`stat -c %y /var/log/apt/history.log | awk -F '.' '{print $1}'`|"
echo "|Primaire gebruiker(s):|-|"
echo "|Overige DNS entry's:|-|"
echo "|Interfaces:|`ip a | grep link/ | wc -l`|"
echo "|Interface naam:|iDRAC|"
echo "|Interface mac:|-|"
echo "|Interface IP:|-|"
echo "`ip a | grep -e lo -e bond -e br -e eth -e vlan -e link/ether -e inet | awk -F '<' '{print $1}' | awk -F 'brd' '{print $1}' | awk -F 'inet6' '{print $1}' | sed 's/link\/ether/|Interface mac:|/g' | sed 's/link\/loopback/|Loopback Interface mac:|/g' | sed 's/inet/|IP Address:|/g'|  sed 's/[0-9]: /|Interface Name:|/'| sed 's/[0-9]|/|/' | sed '/^\s*$/d' | sed 's/    //g' | sed 's/$/|/'`"
echo "|RAM:|`free -h | gawk  '/Mem:/{print $2}'`|"
echo "|Aantal CPU's:|`lscpu | grep 'Socket' | sed 's/Socket(s):             //g'`|"
echo "|Aantal cores per CPU|`lscpu | grep 'socket'  | sed 's/Core(s) per socket:    //g'`|"
echo "|Aantal threats:|`nproc`|"
echo "|Back-up mappen:|-|"
echo "|Back-up schema:|-|"
echo "|Bijzondere geinstalleerde software:|-|"
echo "|Bijzondere configuraties:|-|"
echo "|Commentaar:|-|"
