#!/bin/bash
WARN_VALUE=$1
CRIT_VALUE=$2
if [ "$WARN_VALUE" == "" ] || [ "$CRIT_VALUE" == "" ]
then
  # if any parameter is missing it will print it out and exit.
	echo "No argument supplied or argument missing."
	echo "Usage: ./check_uptime-vars <warning value in days> <critical value in days>"
	echo "Example: ./check_uptime-vars 200 300"
	exit 1
else
  DAYS=$(awk '{printf("%d\n", $1/86400)}' /proc/uptime)
  if [[ "$DAYS" -lt "$WARN_VALUE" ]]; then
    echo "OK. Uptime is $DAYS days."
    exit 0
  fi
  if [ "$DAYS" -ge "$WARN_VALUE" ] && [ "$DAYS" -le "$CRIT_VALUE" ]; then
    echo "WARNING! Uptime is $DAYS days."
    exit 1
  fi
  if [[ "$DAYS" -gt "$CRIT_VALUE" ]]; then
    echo "CRITICAL! Uptime is $DAYS days."
    exit 2
  fi
fi
